### ISSUE TITLE
There are Bugs!!!

### ISSUE THREAD

**Issue by teeradona** [joshavanier/joshavanier.github.io#6]
!!!!
!!!!
!!!!!!!!!!!!!!!!    !!!!      !!!!      !!!!!!!!!!!!!!!!
!!!!        !!!!     !!!!     !!!!      !!!!        !!!!
!!!!!!!!!!!!!!!!     !!!!!!!!!!!!       !!!!!!!!!!!!!!!!
                                                     !!!!
                                         !!!!!!!!!!!!!!!!

**Comment by wickedmiracle** [comment]
Where is Sumitri and Jo Ei Tri ?????
